=== joaopedrocosta2004/ISEC/ID/Countries/factos.dtd
<!ELEMENT factos (facto+)>
<!ELEMENT facto (iso, continente, presidente_republica, imagem, capital, moeda, populacao, crescimento_populacao, area, idiomas_oficiais, cidades_populosas, paises_vizinhos, dominio_internet)>
<!ATTLIST facto nome CDATA #REQUIRED>

<!ELEMENT iso (#PCDATA)>
<!ELEMENT continente (#PCDATA)>
<!ELEMENT presidente_republica (#PCDATA)>
<!ELEMENT imagem (#PCDATA)>
<!ELEMENT capital (#PCDATA)>
<!ELEMENT moeda (#PCDATA)>
<!ELEMENT populacao (#PCDATA)>
<!ELEMENT crescimento_populacao (#PCDATA)>
<!ELEMENT area (#PCDATA)>

<!ELEMENT idiomas_oficiais (idioma+)>
<!ELEMENT idioma (#PCDATA)>

<!ELEMENT cidades_populosas (cidade+)>
<!ELEMENT cidade (#PCDATA)>

<!ELEMENT paises_vizinhos (pais_vizinho+)>
<!ELEMENT pais_vizinho (#PCDATA)>

<!ELEMENT dominio_internet (#PCDATA)>

=== joaopedrocosta2004/ISEC/ID/Countries/factos.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE factos SYSTEM "factos.dtd">
<factos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="factos.xsd">
     <facto nome="Portugal">
          <iso>PT</iso>
          <continente>Europe</continente>
          <presidente_republica>Marcelo Rebelo de Sousa</presidente_republica>
          <imagem>https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Portugal.svg/1200px-Flag_of_Portugal.svg.png</imagem>
          <capital>ola</capital>
          <moeda>USD</moeda>
          <populacao>14</populacao>
          <crescimento_populacao>0.15%</crescimento_populacao>
          <area>14</area>
          <idiomas_oficiais>
               <idioma>Portugues</idioma>
               <idioma>American</idioma>
          </idiomas_oficiais>
          <cidades_populosas>
               <cidade>Lisboa</cidade>
               <cidade>Porto</cidade>
          </cidades_populosas>
          <paises_vizinhos>
               <pais_vizinho>Israel</pais_vizinho>
          </paises_vizinhos>
          <dominio_internet>.pt</dominio_internet>
     </facto>
     <facto nome="Espanha">
          <iso>PT</iso>
          <continente>Europe</continente>
          <presidente_republica>Marcelo Rebelo de Sousa</presidente_republica>
          <imagem>https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Portugal.svg/1200px-Flag_of_Portugal.svg.png</imagem>
          <capital>ola</capital>
          <moeda>USD</moeda>
          <populacao>15</populacao>
          <crescimento_populacao>0.15%</crescimento_populacao>
          <area>12</area>
          <idiomas_oficiais>
               <idioma>Portugues</idioma>
               <idioma>American</idioma>
          </idiomas_oficiais>
          <cidades_populosas>
               <cidade>Lisboa</cidade>
               <cidade>Porto</cidade>
          </cidades_populosas>
          <paises_vizinhos>
               <pais_vizinho>Israel</pais_vizinho>
          </paises_vizinhos>
          <dominio_internet>.pt</dominio_internet>
     </facto>
</factos>
